FROM alpine:3.22 AS builder
FROM scratch
ENV TZ=Asia/Tokyo
ENV SSL_CERT_FILE=/ca-certificates.crt
WORKDIR /app

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /
COPY ./app /
COPY ./target/aarch64-unknown-linux-musl/release/voicemail /app/
ADD  ./assets/ /app/assets/
EXPOSE 8080/tcp
EXPOSE 5060-5070/udp
ENTRYPOINT ["/app/voicemail", "--rec", "--sms"]