FROM gcr.io/distroless/static-debian12:nonroot
ENV TZ=Asia/Tokyo
WORKDIR /app
USER nonroot
COPY --chown=nonroot:nonroot ./target/aarch64-unknown-linux-musl/release/voicemail /app/
COPY --chown=nonroot:nonroot ./voicemail.db /app/
ADD --chown=nonroot:nonroot ./assets/ /app/assets/
ADD --chown=nonroot:nonroot ./recv_voice/ /app/recv_voice/
EXPOSE 8080/tcp
EXPOSE 5060-5070/udp
ENTRYPOINT ["/app/voicemail", "--rec", "--sip-server", "172.17.0.4", "--user", "101", "--password", "101"]
